/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoShowDoMilhao;

/**
 *
 * @author Vinicius Augusto dos Santos Silva
 */
public class JogoDoMilhao extends javax.swing.JFrame {

    private final String perguntasRespostas[][] = new String[5][5];
    private int numPergunta;
    private int ponto;

    /**
     * Creates new form JogoDoMilhao
     */
    public JogoDoMilhao() {
        initComponents();

        numPergunta = 0;
        ponto = 0;
        perguntasDoJogo(perguntasRespostas);
        proximaPergunta(perguntasRespostas);
    }

    /**
     * Instância as perguntas do jogo
     *
     * @param perguntasRespostas
     */
    private void perguntasDoJogo(String[][] perguntasRespostas) {

        //Pergunta 1
        perguntasRespostas[0][0] = "Qual o livro mais lido do mundo?";
        //Alternativas da pergunta 1
        perguntasRespostas[0][1] = "Alice no País das Maravilhas";
        perguntasRespostas[0][2] = "O Pequeno Príncipe";
        perguntasRespostas[0][3] = "Bíblia Sagrada";
        perguntasRespostas[0][4] = "Harry Potter e a Pedra Filosofal";

        //Pergunta 2
        perguntasRespostas[1][0] = "Em que ano teve o fim da segunda guerra mundial?";
        //Alternativas da pergunta 2
        perguntasRespostas[1][1] = "1912";
        perguntasRespostas[1][2] = "1929";
        perguntasRespostas[1][3] = "1945";
        perguntasRespostas[1][4] = "1966";

        //Pergunta 3
        perguntasRespostas[2][0] = "Qual a invenção mais importante do mundo?";
        //Alternativas da pergunta 3
        perguntasRespostas[2][1] = "Matemática";
        perguntasRespostas[2][2] = "Alfabeto";
        perguntasRespostas[2][3] = "Ser humano";
        perguntasRespostas[2][4] = "Eletricidade";

        //Pergunta 4
        perguntasRespostas[3][0] = "Qual a capital da Grécia?";
        //Alternativas da pergunta 4
        perguntasRespostas[3][1] = "Atenas";
        perguntasRespostas[3][2] = "Olímpia";
        perguntasRespostas[3][3] = "Delfos";
        perguntasRespostas[3][4] = "Esparta";

        //Pergunta 5
        perguntasRespostas[4][0] = "Qual o maior país do mundo?";
        //Alternativas da pergunta 5
        perguntasRespostas[4][1] = "Brasil";
        perguntasRespostas[4][2] = "Russia";
        perguntasRespostas[4][3] = "EUA";
        perguntasRespostas[4][4] = "China";

    }

    /**
     * Carrega as proximas perguntas e alternativas
     *
     * @param perguntasRespostas
     */
    private void proximaPergunta(String[][] perguntasRespostas) {

        if (numPergunta < 5 && numPergunta >= 0) {

            jLabelPergunta.setText(perguntasRespostas[numPergunta][0]);

            //Alternativas
            jLabelAlt1.setText(perguntasRespostas[numPergunta][1]);
            jLabelAlt2.setText(perguntasRespostas[numPergunta][2]);
            jLabelAlt3.setText(perguntasRespostas[numPergunta][3]);
            jLabelAlt4.setText(perguntasRespostas[numPergunta][4]);
        } else {
            jLabelResultado.setText("Acertou " + ponto + " perguntas.");
            desabilitarBotoes();
        }

    }

    /**
     * Desabilita os botoes das alternativas.
     */
    public void desabilitarBotoes() {
        jButtonAlt1.setEnabled(false);
        jButtonAlt2.setEnabled(false);
        jButtonAlt3.setEnabled(false);
        jButtonAlt4.setEnabled(false);

    }

    /**
     * Verifica se a resposta esta correta e realiza a soma dos pontos
     *
     * @param pergunta
     * @param resposta
     */
    public void verificaResposta(int pergunta, int resposta) {

        switch (pergunta) {

            case 0:
                if (resposta == 3) {
                    ponto++;
                }
                numPergunta++;
                break;

            case 1:
                if (resposta == 3) {
                    ponto++;
                }
                numPergunta++;
                break;

            case 2:
                if (resposta == 3) {
                    ponto++;
                }
                numPergunta++;
                break;

            case 3:
                if (resposta == 1) {
                    ponto++;
                }
                numPergunta++;
                break;

            case 4:
                if (resposta == 2) {
                    ponto++;
                }
                numPergunta++;
                break;

            default:
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPergunta = new javax.swing.JLabel();
        jButtonAlt1 = new javax.swing.JButton();
        jButtonAlt2 = new javax.swing.JButton();
        jButtonAlt3 = new javax.swing.JButton();
        jButtonAlt4 = new javax.swing.JButton();
        jLabelAlt4 = new javax.swing.JLabel();
        jLabelAlt1 = new javax.swing.JLabel();
        jLabelAlt2 = new javax.swing.JLabel();
        jLabelAlt3 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo do Milhao");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPergunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPergunta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPergunta.setText("Questão");
        jLabelPergunta.setToolTipText("");
        jLabelPergunta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelPergunta.setAutoscrolls(true);
        jLabelPergunta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelPergunta.setFocusTraversalPolicyProvider(true);
        jLabelPergunta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelPergunta.setName(""); // NOI18N
        getContentPane().add(jLabelPergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 40));

        jButtonAlt1.setText("A");
        jButtonAlt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jButtonAlt2.setText("B");
        jButtonAlt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlt2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButtonAlt3.setText("C");
        jButtonAlt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlt3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jButtonAlt4.setText("D");
        jButtonAlt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlt4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabelAlt4.setText("Alternativas");
        getContentPane().add(jLabelAlt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 20));

        jLabelAlt1.setText("Alternativas");
        getContentPane().add(jLabelAlt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabelAlt2.setText("Alternativas");
        getContentPane().add(jLabelAlt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 20));

        jLabelAlt3.setText("Alternativas");
        getContentPane().add(jLabelAlt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        jLabelResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 360, -1));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlt1ActionPerformed
        verificaResposta(numPergunta, 1);
        proximaPergunta(perguntasRespostas);
    }//GEN-LAST:event_jButtonAlt1ActionPerformed

    private void jButtonAlt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlt2ActionPerformed
        verificaResposta(numPergunta, 2);
        proximaPergunta(perguntasRespostas);
    }//GEN-LAST:event_jButtonAlt2ActionPerformed

    private void jButtonAlt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlt3ActionPerformed
        verificaResposta(numPergunta, 3);
        proximaPergunta(perguntasRespostas);
    }//GEN-LAST:event_jButtonAlt3ActionPerformed

    private void jButtonAlt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlt4ActionPerformed
        verificaResposta(numPergunta, 4);
        proximaPergunta(perguntasRespostas);
    }//GEN-LAST:event_jButtonAlt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDoMilhao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDoMilhao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDoMilhao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDoMilhao.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDoMilhao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlt1;
    private javax.swing.JButton jButtonAlt2;
    private javax.swing.JButton jButtonAlt3;
    private javax.swing.JButton jButtonAlt4;
    private javax.swing.JLabel jLabelAlt1;
    private javax.swing.JLabel jLabelAlt2;
    private javax.swing.JLabel jLabelAlt3;
    private javax.swing.JLabel jLabelAlt4;
    private javax.swing.JLabel jLabelPergunta;
    private javax.swing.JLabel jLabelResultado;
    // End of variables declaration//GEN-END:variables
}
